components.json, package-lock.json, package.json, src/lib/utils.ts, src/styles/globals.css, tailwind.config.ts
> Shadcn/ui 설치했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/8
- 작업 전에 pull하고 ```npm install``` 한 번 해주세요
close #[8]
=> Shadcn/ui 설치 및 세팅

src/services/api.ts
로그아웃 api 추가 및 url 수정, 로그인 필요/필요없음 구분 했습니다. 
바로 머지해주시면 됩니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/32
close #32
=> axios/api 파일 수정

src/lib/Date.ts
day.js 함수 파일 생성
> https://github.com/Team-YUMU/YUMU-FE/issues/37
close #37
=> day.js 파일 생성

src/components/domain/myPage/Tabs/Edit/Edit.tsx, src/components/ui/AuthInput.tsx, src/components/ui/alert-dialog.tsx, src/components/ui/button.tsx, src/components/ui/textarea.tsx, src/pages/mypage/index.tsx, src/styles/globals.css, src/types/newPwdValidation.ts, src/types/validation.ts
feat
- myPage 전용 validation을 생성 및 데이터 패칭 전 디자인 구성 및 기능 구현 했습니다.
fix
- validation.ts  에러메세지 내용 수정 했습니다. 
style
- 버튼 스타일 수정 및 box-sizing : border-box 선언했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/53
close #53
=> Edit 컴포넌트 수정

src/components/common/AuctionDetail.tsx, src/components/domain/live/livebids.tsx, src/pages/auction/[auctionid]/streaming/index.tsx
- 별거 아니고 공지글 파트 지우고, space 조금 처리하고, livebids 컴포넌트를 stick 시켰습니다. 그리고 아티스트가 보는 화면을 streaming으로 따로 만들었어요.
> https://github.com/Team-YUMU/YUMU-FE/issues/58
close #58
=>  LiveAuction 페이지 분리 (구매자와 판매자)

src/components/common/Layout.tsx, src/pages/_app.tsx
> Layout 적용 예외 path (/_error', '/404', '/signin', '/signup', '/mypage) 추가 작업했습니다.
> LayoutProps 타입 네이밍 수정했습니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/[47]
close #47
=> refactor: Layout 적용 예외 path 추가

src/components/common/SubLayout.tsx, src/pages/_app.tsx
> mypage에서 header, main만 나오도록 예외 레이아웃 추가 작업하였습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/65
close #65
=> 예외 페이지 SubLayout 추가

package-lock.json, package.json, src/components/common/Modal.tsx, src/components/ui/AuthInput.tsx, src/components/ui/button.tsx, src/pages/index.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx
Singin, Signup 페이지에서 사용하는 AuthInput 과 Button ui를 수정했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/82
close #82
=> AuthInput, Button 수정

src/components/ui/AuthInput.tsx, src/components/ui/ErrorMessage.tsx, src/pages/index.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/services/api.ts
기능구현중인데 api가 오류나서 일단 푸쉬합니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/91
close #91
=> 회원가입,로그인 페이지 오류 수정

src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/types/types.ts, src/types/validator/signForm.ts
zod 수정 후 회원가입 페이지 기능 구현 일부 했습니다. 
로그인페이지 토큰 관리 관련해서 수정중에 있습니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/101
close #101
=> 회원가입 유효성오류, 로그인 페이지 오류 수정

package-lock.json, package.json, src/services/api.ts, src/services/axios.ts
…als = true;
선언 제거
react-cookie 라이브러리 삭제 및 axios 쿠키 설정 관련 선언 제거했습니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/110
close #110
=> axios/api 파일 및 package.json 수정

src/pages/signin/index.tsx, src/pages/signup/index.tsx
Signup/in 페이지 카카오 로그인 완료 및 로그인 유효성 에러 검사 하려 했지만 버그가 생겨 수정했습니다. 동시에 103 브랜치를 강제 푸쉬 해서 그런지 pr 요청이 되지 않아 일단 머지  되었고 ,, 103 브랜치 닫겠습니다.
담부터 강제푸쉬는 사용을 지양하겠습니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/115
close #115
close #103
=> Signup/in 페이지 카카오 로그인 완료 및 로그인 유효성 에러 검사

next.config.mjs, public/svgs/m1-timeNear-l.svg, public/svgs/m1-timeNear-r.svg, src/components/common/ExhibitionCarousel.tsx, src/components/common/Header.tsx, src/components/common/SearchForm.tsx, src/components/domain/landing/LandingBanner.tsx, src/components/ui/input.tsx, src/pages/landing/index.tsx, src/styles/globals.css
> pr 내용을 간략히 설명해주세요
- landding 페이지의 현재라이브 경매 / 인기 경매 구현 UI 작업과  API 작업을 진행했습니다.
미진행) 현재라이브 경매의 [실시간 남은 시간 / 라이브 제목 아래 상세 내용 API] 
> https://github.com/Team-YUMU/YUMU-FE/issues/77
close #77
=> Feat/hyun522/77 main 페이지 현재라이브경매 / 인기경매 구현 

src/components/common/BestAuction.tsx, src/pages/auction/[auctionid]/detail/index.tsx
> 인기 경매 리스트 섹션이 메인페이지, 상세페이지에서 공통적으로 쓰여서 리팩토링 했습니다. 
> 목업 데이터로 작업되어 있습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/129
close #129
=>  인기 경매 리스트 공통 컴포넌트로 리팩토링

package-lock.json, package.json, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/services/api.ts, src/types/validator/signForm.ts
로그인 회원가입 페이지가 서버에러로 동작하지 않아서 기다리고있습니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/117
close #117
=> 카카오로그인 및 로그인유효성검사 에러수정

src/pages/signin/index.tsx, src/types/validator/signForm.ts
카카오 로그인 api요청을 수정했습니다. CORS 에러가 나서 이부분 백엔드 팀과 이야기 중에 있습니다. 
로그인 회원가입 기능에는 문제 없습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/131
close #131
=> chore: 브랜치정리

public/svgs/arrow_first.svg, public/svgs/arrow_last.svg, public/svgs/arrow_next.svg, public/svgs/arrow_prev.svg, public/svgs/chevron_down.svg, src/components/common/Pagination.tsx, src/components/common/SearchForm.tsx, src/components/common/SortSelect.tsx, src/pages/search/index.tsx
> Pagination 컴포넌트 디자인 시안 적용했습니다.
> Pagination first, last 페이지 이동 버튼 추가 했습니다.
> SortSelect 컴포넌트 디자인 시안 적용 및 기능 수정했습니다.
> AuctionCard 리스트 레이아웃 디자인 시안 적용했습니다. 
> 내일 백엔드 민수님하고 API 테스트 해보겠습니다.
https://github.com/Team-YUMU/YUMU-FE/assets/97681668/4c66d002-bc60-4a6e-80ad-a862f1b05758
> https://github.com/Team-YUMU/YUMU-FE/issues/128
close #128
=> 검색 페이지 디자인 시안 적용 및 기능 수정

src/components/common/AuctionDetail.tsx, src/components/common/BestAuction.tsx, src/components/domain/landing/LandingLivePopular.tsx, src/pages/auction/[auctionid]/detail/index.tsx, src/pages/auction/[auctionid]/live/index.tsx, src/pages/auction/[auctionid]/streaming/index.tsx, src/pages/landing/index.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx, src/styles/globals.css, tailwind.config.ts
> 잠실체 적용된 폰트 전체 수정했습니다. 
> 이후 작업부터는 font-TheJamsil 로 적용하시면 됩니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/142
close #142
=> design: 잠실체 적용된 폰트 전체 수정

package-lock.json, package.json, src/pages/callback/index.tsx, src/pages/signin/callback/index.tsx, src/pages/signin/index.tsx, src/services/api.ts
카카오 로그인 토큰 가져오는것 관련해서 멘토님과 코드 보기위해 pr 합니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/137
close #137
=> 카카오 로그인 토큰가져오기 시도중입니다.

src/components/common/Header.tsx
header작업
> https://github.com/Team-YUMU/YUMU-FE/issues/125
close #125
=> feat : header 공동 컴포넌트 작업

src/components/domain/myPage/Tabs/Edit/Edit.tsx, src/components/domain/myPage/Tabs/Edit/NewPasswordModalForm.tsx, src/components/domain/myPage/Tabs/Edit/UserDeleteModal.tsx, src/components/ui/AuthInput.tsx, src/pages/callback/index.tsx, src/pages/mypage/index.tsx, src/pages/signin/index.tsx, src/services/api.ts, src/types/types.ts, src/types/validator/myPageForm.ts, src/types/validator/signForm.ts
마이페이지 정보수정 기능 구현 다 한것같슴다.. 
api 파일 수정좀 했으니 참고 부탁드려요 ! 
은지님은 카카오 로그인 코드 참고해주세요 ! 
> https://github.com/Team-YUMU/YUMU-FE/issues/159
close #159
=> 마이페이지 정보 수정 기능 구현 마무리 작업

src/components/common/AuctionDetail.tsx, src/components/common/InfoBox.tsx, src/components/domain/live/BiddingBox.tsx, src/pages/auction/[auctionid]/live/index.tsx, src/pages/auction/[auctionid]/streaming/index.tsx, src/styles/globals.css, src/types/types.ts
- 최신 UI 적용했습니다. (BiddingBox)
- 가볍게 getAuctionDetails 해서 데이터 넣을 수 있도록 했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/149
- 같은 AuctionDetail 컴포넌트를 공유하는 detail 페이지에서 충돌이 발생합니다. 일단 props를 모두 optional로 해서 해결했습니다만, 나중에 참고 바랍니다.
close #149
=> live 페이지 최신 UI 적용

src/pages/signin/index.tsx
env.local 에 카카오 로그인 어플리케이션의 개인 키를 저장해뒀습니다. 
풀 받아오실 때 중요한 정보들은 따로 말씀드리겠습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/186
close #186
=> .env.local 작성 , 적용 완료

src/components/domain/myPage/Tabs/BuyHistory.tsx, src/components/domain/myPage/Tabs/Edit/IntroEditForm.tsx, src/components/domain/myPage/Tabs/Edit/NewPasswordModalForm.tsx, src/components/domain/myPage/Tabs/Edit/NickNameEditForm.tsx, src/components/domain/myPage/Tabs/SalesHistory.tsx, src/components/domain/myPage/Tabs/WishList.tsx, src/pages/mypage/index.tsx, tailwind.config.ts
pr 테스트
> https://github.com/Team-YUMU/YUMU-FE/issues/190
close #190
=> 수정 컴포넌트 쿼리 적용 및 목록 클릭시 해당 상세페이지로 이동 구현

src/components/common/InfoBox.tsx, src/pages/registration/index.tsx
- 경매 등록하기 버튼 하단에도 추가
- InfoBox에 truncate 적용
- 경매 요약 입력란에 300자 제한 적용
> https://github.com/Team-YUMU/YUMU-FE/issues/198
close #198
=> 경매 등록 UI 일부 수정

src/pages/registration/index.tsx
> https://github.com/Team-YUMU/YUMU-FE/issues/
close #[이슈번호]
=> 경매 등록 페이지 Textarea scrollbar-hide 및 잘못된 최대 입력자 제한 해제

src/components/common/AuctionCard.tsx, src/components/common/AuctionDetailHeader.tsx, src/pages/auction/[auctionid]/detail/index.tsx, src/pages/landing/index.tsx
> 상세 페이지와 AuctionCard에 들어가는 데이터 수정했습니다.
> artSummary 4줄 이상시 말줄임 처리로 수정했습니다.
> AuctionDetailHeader 공통 컴포넌트 작업했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/202
close #202
=> 상세 페이지 디자인 디테일 수정 및 데이터 바인딩 수정

src/components/domain/myPage/Tabs/BuyHistory.tsx, src/components/domain/myPage/Tabs/Edit/IntroEditForm.tsx, src/components/domain/myPage/Tabs/SalesHistory.tsx, src/components/domain/myPage/Tabs/WishList.tsx, src/services/api.ts
api / mypage 리팩토링 했습니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/
close #213
=> 마이페이지 리팩토링

src/components/common/Header.tsx, src/pages/_app.tsx
로그인/회원가입 페이지 헤더 설정했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/215
close #215
=> 로그인/회원가입  페이지 헤더 설정

src/pages/signin/index.tsx, src/services/api.ts
로그인 페이지 사용자 정보 없음(404) 모달 작성 했습니다.
api 파일에서 로그인 관련 api도 수정했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/186
close #186
=>  로그인 페이지 사용자 정보 없음(404) 모달 작성

src/components/domain/live/BidHistories.tsx, src/components/domain/live/chats.tsx, src/components/domain/live/livechatting.tsx, src/pages/chatting/[roomId].tsx
- livechatting 컴포넌트에 실시간 채팅 적용
> https://github.com/Team-YUMU/YUMU-FE/issues/208
close #208
=> 소켓 연결부터 구독 및 채팅까지 live 페이지에 적용

src/components/domain/myPage/Tabs/BuyHistory.tsx, src/components/domain/myPage/Tabs/SalesHistory.tsx, src/components/domain/myPage/Tabs/WishList.tsx, src/pages/_app.tsx, src/pages/signin/index.tsx, src/pages/signup/index.tsx
마이페이지 로그인/회원가입 페이지 스타일 수정했습니다. 
> https://github.com/Team-YUMU/YUMU-FE/issues/231
close #231
=> 마이페이지, 로그인/회원가입 페이지 스타일 수정

src/components/domain/live/livechatting.tsx
> https://github.com/Team-YUMU/YUMU-FE/issues/233
close #233
=> 채팅 누적 실패 버그 해결

src/components/domain/live/chats.tsx, src/components/domain/live/livechatting.tsx
- 내가 승리자다
> https://github.com/Team-YUMU/YUMU-FE/issues/230
close #230
=> 실시간 채팅에 본인 닉네임을 memberId로 전달하는 기능 추가

src/components/domain/landing/LandingBanner.tsx, src/pages/landing/index.tsx
> https://github.com/Team-YUMU/YUMU-FE/issues/223
close #223
=> 랜딩페이지 환경 변수 추가

src/components/domain/live/BidHistories.tsx, src/components/domain/live/CurrentBidBox.tsx, src/pages/auction/[auctionid]/live/index.tsx
- CurrentBidBox 추가
> https://github.com/Team-YUMU/YUMU-FE/issues/227
- 본래 웹소켓으로 진행 예정이었으나, 설계 변경과 시간 자원의 부족으로 인하여 중간 결과물 푸시합니다.
close #227
=> 현재 입찰가 웹소켓 연결(기획 변경됨)

src/components/domain/myPage/Tabs/WishList.tsx
찜 목록 하트 버튼 마우스 호버하면 빈 하트 나오게 수정했습니다.
> https://github.com/Team-YUMU/YUMU-FE/issues/240
close #240
=> 찜 목록 Query Key 값 수정 및 하트 버튼 호버시 빈 하트 되게 수정

src/pages/signup/index.tsx
회원가입 완료가 안되는 문제 해결
> https://github.com/Team-YUMU/YUMU-FE/issues/249
close #249
=>  회원가입 완료가 안되는 문제 해결

src/pages/_app.tsx
Mixed content 에러 해결 
> https://github.com/Team-YUMU/YUMU-FE/issues/263
close #263
=> Mixed content 에러 해결

next.config.mjs, package.json, src/pages/_app.tsx, src/services/axios.ts
http -> https 로 변경 및 CORS 관련 Proxy 우회 설정 제거
> https://github.com/Team-YUMU/YUMU-FE/issues/267
close #267
=> net::ERR_SSL_PROTOCOL_ERROR 에러 해결

next.config.mjs, package.json, src/pages/_app.tsx, src/services/axios.ts
> https://github.com/Team-YUMU/YUMU-FE/issues/
close #[이슈번호]
=> fix : http -> https 로 변경 및 CORS 관련 Proxy 우회 설정 제거 (#268)
